### ISSUE TITLE
wrong ELF class: ELFCLASS32 on raspberry pi os lite 64bit

### ISSUE THREAD

**Issue by TimoBuechert** [manusa/helm-java#209] opened 2024-11-19 12:43 UTC
Hi! I am trying to run a spring boot app with the latest helm-java (0.0.13) on a raspberrypi running Raspberry Pi OS Lite 64 bit. 
Sadly, the call to helm fails with the following message:

Caused by: java.lang.UnsatisfiedLinkError: Unable to load library '/tmp/helm-java16438086015481545622/helm-linux-arm64.so':
/tmp/helm-java16438086015481545622/helm-linux-arm64.so: wrong ELF class: ELFCLASS32

When running the app with helm-java 0.0.9 it works. 

Do i need to upgrade other dependencies for the latest helm-java to be compatible?

Thanks very much! Best, Timo

**Comment by manusa** [comment] 2024-11-19 14:49
> Hi! I am trying to run a spring boot app with the latest helm-java (0.0.13) on a raspberrypi running Raspberry Pi OS Lite 64 bit.

Wow, I really didn't expect anyone to be using this on a Raspberry, that's really cool :smile:

You mention it was working in 0.0.9, have you checked on 0.0.10 and subsequent? it would be helpful to identify where things started to fail, it might be due to a Go dependency.

**Comment by manusa** [comment] 2024-11-19 15:01
Might be related to https://github.com/techknowlogick/xgo/issues/256

**Comment by TimoBuechert** [comment] 2024-11-22 09:52
Thanks! At the moment it is still more of a research project 😄 I'll try the subsequent versions and let you know. Thanks for getting back to me!

**Comment by bkowalik** [comment] 2024-11-26 08:57
@manusa I can confirm that it fails on AWS Graviton instances as well.

**Comment by manusa** [comment] 2024-11-27 10:59
> @manusa I can confirm that it fails on AWS Graviton instances as well.

Hi @bkowalik,
It's impossible for me to reproduce this issue since I don't have the required infra.
Would it be possible for you to help me bisect the version where the problem was introduced?

**Comment by manusa** [comment] 2024-11-28 09:59
Thx! 
Have you tried 0.0.14 which was released yesterday?

**Comment by bkowalik** [comment] 2024-11-28 10:14
Thanks, I have not noticed the latest release. I confirm that version `0.0.14` works like a charm.

**Comment by manusa** [comment] 2024-11-28 10:37
Awesome, thx!
I'll wait for @TimoBuechert to confirm it's working for him too and will close the issue.

**Comment by TimoBuechert** [comment] 2024-12-20 18:09
It works for me as well, thank you very much!

**Closed** 2024-12-21 03:08 UTC
